config/routes.rb
Rails.application.routes.draw do

  root 'feeds#index'

  resources :feeds do
    get :end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord

  def set_time
    if self.end.present?
      (( self.end - self.created_at ) / 60).round(0)
    else
      "-"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all.order(id: :desc)
    @feed = Feed.new
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
    @feed.save
    # redirect_to edit_feed_path(@feed)
    redirect_to feeds_path
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    @feed.save
    redirect_to feeds_path
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    @feed.update(feed_params)
    # @feed.time = ((@feed.end - @feed.created_at) / 60).round.to_i
    @feed.end = DateTime.current
    @feed.save
    redirect_to feeds_path
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:start, :end, :breast, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def rightleft(x)
  x ? "Right" : "Left"
end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>

  <div class="chest">
    <div class="breast" id="left">
      <div class="areola">
        <div class="nipple">
        </div>
      </div>
    </div>
    <div class="breast" id="right">
      <div class="areola">
        <div class="nipple">
        </div>
      </div>
    </div>
  </div>

  <div id="time">
      <%= feed.created_at.strftime('%H:%M') %>
      <!-- <span id="minutes">0</span>:<span id="seconds">00</span> -->
  </div>

  <%= form.submit "Log", id: "stopBtn" %>

  <div style="display:none">
    <%= form.datetime_select :start %><br>
    <%= form.datetime_select :end %><br>
    <%= form.check_box :breast %><br>
    <%= form.number_field :time %>
  </div>

<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#right').css('opacity','0.5');
  });
  $('#left').click(function(){
    $('#feed_breast').prop('checked', false);
    $('.breast').css('opacity','0.5');
    $(this).css('opacity','1');
  });
  $('#right').click(function(){
    $('#feed_breast').prop('checked', true);
    $('.breast').css('opacity','0.5');
    $(this).css('opacity','1');
  });
  // STOPWATCH
  $(function() {

    var hours = minutes = seconds = milliseconds = 0;
    var prev_hours = prev_minutes = prev_seconds = prev_milliseconds = undefined;
    var timeUpdate;

    $(document).ready(function(){
      updateTime(0,0,0,0);
    });

    // Update time in stopwatch periodically - every 25ms
    function updateTime(prev_minutes, prev_seconds){
        var startTime = new Date();    // fetch current time
        timeUpdate = setInterval(function () {
            var timeElapsed = new Date().getTime() - startTime.getTime();    // calculate the time elapsed in milliseconds
            // calculate minutes
            minutes = parseInt(timeElapsed / 1000 / 60) + prev_minutes;
            if (minutes > 60) minutes %= 60;
            // calculate seconds
            seconds = parseInt(timeElapsed / 1000) + prev_seconds;
            if (seconds > 60) seconds %= 60;
            // set the stopwatch
            setStopwatch(minutes, seconds);
        }, 25); // update time in stopwatch after every 25ms

    }

    // Set the time in stopwatch
    function setStopwatch(minutes, seconds){
        $("#minutes").html(prependZero(minutes, 1));
        $("#seconds").html(prependZero(seconds, 2));
    }

    // Prepend zeros to the digits in stopwatch
    function prependZero(time, length) {
        time = new String(time);    // stringify time
        return new Array(Math.max(length - time.length + 1, 0)).join("0") + time;
    }
});
</script>

app/views/feeds/edit.html.erb
<%= render 'form', feed: @feed %>

app/views/feeds/index.html.erb
<!-- <div class="start">
  <%= link_to 'Start', new_feed_path, id: "stopBtn" %>
</div> -->

<div id="indexForm">
  <%= form_for(@feed) do |form| %>
    <div class="chest">
      <div class="breast" id="left">
        <div class="areola">
          <div class="nipple">
          </div>
        </div>
      </div>
      <div class="breast" id="right">
        <div class="areola">
          <div class="nipple">
          </div>
        </div>
      </div>
    </div>
    <%= form.submit "Log", id: "stopBtn" %>
    <div style="display:none">
      <%= form.datetime_select :start %><br>
      <%= form.datetime_select :end %><br>
      <%= form.check_box :breast %><br>
      <%= form.number_field :time %>
    </div>
  <% end %>
</div>

<% @feeds.each_with_index do |feed, i| %>
<div class="feed" id="feed<%= i %>">
  <span><%= link_to '&#10005;'.html_safe, feed, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" %></span>
  <p class="meta"><%= feed.created_at.strftime('%a %H:%M') %></p>
  <h2><%= rightleft(feed.breast) %></h2>
  <!-- <p><%= feed.set_time %> mins</p> -->
</div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#right').css('opacity','0.5');
  });
  $('#left').click(function(){
    $('#feed_breast').prop('checked', false);
    $('.breast').css('opacity','0.5');
    $(this).css('opacity','1');
  });
  $('#right').click(function(){
    $('#feed_breast').prop('checked', true);
    $('.breast').css('opacity','0.5');
    $(this).css('opacity','1');
  });
</script>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @feed.created_at %>
</p>

<p>
  <strong>End:</strong>
  <%= @feed.end %>
</p>

<p>
  <strong>Breast:</strong>
  <%= rightleft(@feed.breast) %>
</p>

<p>
  <strong>Time:</strong>
  <%= @feed.time %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simply the Breast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>